// UNUSED — not imported anywhere in social-banner-block. The block's actual
// icon list is ./bootstrapIcons.js (2,078 icons, generated by ./bicons.js),
// wired in via BootstrapIconPicker.js. This tiny 2-entry sample is stale
// leftover scaffolding; kept only so nothing that might reference it
// elsewhere breaks, with its typo (missing "b" in "bi bi-heart") fixed.
export const icons = [
    {
        icon: "Star",
        class: "bi bi-star"
    },
    {
        icon: "Heart",
        class: "bi bi-heart"
    }
];
