import './categories';
import './responsive-system';
import './get-started-tour';
import './scroll-text-block';
import './particles-block';
import "./questions-block";
import './portfolio-block';
import './project-block';
import './services-block';
import './button-block';
import "./case-studies-block";
import "./video-hero-block";
import "./testimonial-block";
import "./logos-block";
import "./cta-block";
import "./call-to-action-block";
import './accordion-block';
import './accordion-item-block';
import './tabs-block';
import './tab-panel-block';
import './posts-grid-block';
import './posts-carousel-block';
import "./counter-block";
import "./mega-menu-block";
import "./mega-menu-panel-block";
import "./map-block"
import "./video-player-block"
import "./animation-scroll-block"
import "./icon-box-block"
import "./flipcard-block"
import "./flipcard-front-block"
import "./flipcard-back-block"
import "./popup-modal-block"
import "./industries-block"
import "./testimonial2-block"
import "./testimonial3-block"
import "./our-process-block"
import "./swiper-carousel-block"
import "./swiper-slide-block"
import "./content-toggle-block"
import "./content-toggle-panel-block"
import "./video-carousel-block"
import "./social-share-block"
import "./pricing-table-block"
import "./progress-block"
import "./container-block"
import "./hero-banner-block"
// Legacy alias — keeps pages saved under the old create-block/hero-1-block
// name fully editable/renderable. Hidden from the inserter (supports.inserter
// is false in its block.json); do not remove without a content migration.
import "./hero-1-block"
import "./infogrid-2-block"
import "./infogrid-3-block"
import "./bento-grid-block"
import "./image-composition-block"
import "./header-block"
import "./website-footer-block"
import "./contact-cards-block"
import "./horizontal-scroll-carousel-block"
import "./horizontal-scroll-card-block"


import "./saas-hero-block"
import "./skill-bar-block"
import "./form-block"
import "./form-block"
import "./app-download-block"
import "./pdf-upload-block"
import "./reader-block"
import "./cookie-consent-block"
import "./cookie-notice-block"
import "./promo-banner-block"
import "./live-streamer-block"
import "./column-block"
import "./row-block"
import "./timeline-block"
import "./about-us-block"


